monthoya/monthoya/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings 
from django.conf.urls.static import static

# Add this it change the header of the admin panel. 
admin.site.site_header = 'Admin - Monthoya'
admin.site.index_title = 'Aplicação utilizada para administrar website www.monthoya.com.br'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monthoya/website/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', homepage, name="homepage"),
    path('imoveis/', imoveis, name="imoveis"),
    path('imoveis-views/', imoveis_views, name="imoveis_views"),
    path('contato/', contato, name="contato"),
    path('imovel/<int:id_imovel>/', ver_imovel, name="ver_imovel"),
]

monthoya/website/models.py
from django.db import models
from datetime import datetime
from django.utils.html import format_html

# Create your models here.

class Funcionario(models.Model):
    nome = models.CharField(max_length=300, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    foto = models.ImageField(null=False, blank=False, default='user-default.png')
    cargo = models.CharField(max_length=200, null=True, blank=True)
    descricao = models.TextField()

    class Meta:
        verbose_name = "Funcionário"
        verbose_name_plural = "Funcionários"

    def __str__(self):
        return f'{self.nome} | {self.cargo} | {self.email}'


class Bairro(models.Model):
    descricao = models.CharField(max_length=600, null=True, blank=True)
    isHomepage = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Bairro"
        verbose_name_plural = "Bairros"

    def __str__(self):
        return f'{self.descricao}'
    


TIPOS = (
    ('Apartamento', 'Apartamento'),
    ('Casa/Sobrado', 'Casa/Sobrado'),
    ('Terreno', 'Terreno')
)

OBJETIVOS = (
    ('VENDA', 'VENDA'), 
    ('ALUGA', 'ALUGA')
)

class Imovel(models.Model):
    thumbnail = models.ImageField(null=True, blank=True)
    titulo = models.CharField(max_length=600, null=True, blank=True)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    tipo = models.CharField(max_length=100, null=True, blank=True, choices=TIPOS)
    objetivo = models.CharField(max_length=50, null=True, blank=True, choices=OBJETIVOS)
    ativo = models.BooleanField(default=True)
    destaque = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(null=True, blank=True, default=datetime.now())
    bairro = models.ForeignKey(Bairro, null=True, blank=True, on_delete=models.SET_NULL)
    endereco = models.CharField(max_length=600, null=True, blank=True)
    cidade = models.CharField(max_length=200, null=True, blank=True, default='Paranavaí-PR')
    descricao = models.TextField(null=True, blank=True)
    qtde_quartos = models.IntegerField(default=0)
    qtde_suites = models.IntegerField(default=0)
    qtde_banheiros = models.IntegerField(default=0)
    qtde_vagas = models.IntegerField(default=0)
    qtde_vagas_coberta = models.IntegerField(default=0)
    area_total = models.IntegerField(default=0)
    area_construida = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Imóvel"
        verbose_name_plural = "Imóveis"

    def __str__(self):
        return self.titulo
    

class ImovelFoto(models.Model):
    imagem = models.ImageField(null=True, blank=True)
    imovel = models.ForeignKey(Imovel, null=True, blank=True, on_delete=models.CASCADE)
    
    def image_tag(self):
         return format_html('<img src="{}" style="max-width:100px; max-height:100px"/>'.format(self.imagem.url))


STATUS = (
    ("RESPONDER", "RESPONDER"),
    ("RESPONDIDO", "RESPONDIDO"),
)

class ImovelContato(models.Model):
    imovel = models.ForeignKey(Imovel, null=True, blank=True, on_delete=models.CASCADE)
    nome = models.CharField(max_length=200, null=True, blank=True)
    assunto = models.CharField(max_length=300, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    mensagem = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, null=True, blank=True, choices=STATUS, default="RESPONDER")
    data_criacao = models.DateTimeField(null=True, blank=True, default=datetime.now())

    class Meta:
        verbose_name = "Contato pelo Imóvel"
        verbose_name_plural = "Contatos pelo Imóveis"
    
    def __str__(self):
        return '' #'Título: {}, Preço: {}, Objetivo: {}, Tipo: {} '.format(self.imovel.titulo, self.imovel.preco, self.imovel.objetivo, self.imovel.tipo)



class Contato(models.Model):
    nome = models.CharField(max_length=300, null=True, blank=True)  
    email = models.CharField(max_length=200, null=True, blank=True)
    assunto = models.CharField(max_length=300, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    mensagem = models.TextField()
    status = models.CharField(max_length=20, null=True, blank=True, choices=STATUS, default="RESPONDER")
    data_criacao = models.DateTimeField(null=True, blank=True, default=datetime.now())

    class Meta:
        verbose_name = "Contato"
        verbose_name_plural = "Contatos"

    def __str__(self):
        return ''

monthoya/website/views.py
from django.shortcuts import render, redirect
from .models import *

# Create your views he
def homepage(request):
    imoveis = Imovel.objects.filter(ativo=True).order_by('titulo')
    imoveis_destaque = imoveis.filter(destaque=True).order_by("titulo")
    bairros = Bairro.objects.filter(isHomepage=True).order_by("descricao")  
            
    context = {"imoveis": imoveis, "imoveis_destaque": imoveis_destaque, "bairros": bairros}
    return render(request, 'homepage.html', context)


def imoveis(request):
    imoveis = Imovel.objects.filter(ativo=True).order_by('titulo')
    context = {"imoveis": imoveis}
    return render(request, 'imoveis.html', context)


def imoveis_views(request):
    imoveis = Imovel.objects.filter(ativo=True).order_by('titulo')
    imoveis_views = imoveis.order_by("-views")       
    context = {"imoveis_views": imoveis_views}
    return render(request, 'imoveis-views.html', context)


def ver_imovel(request, id_imovel):
    imovel = Imovel.objects.get(id=id_imovel)
    if request.method == "POST":
        dados = request.POST.dict()
        imovelContato = ImovelContato.objects.create(imovel=imovel,
                                         nome=dados.get("nome"), 
                                         email=dados.get("email"), 
                                         assunto=dados.get("assunto"),
                                         telefone=dados.get("telefone"),
                                         mensagem=dados.get("mensagem"))
        imovelContato.save()
        return redirect("homepage")        
    else:        
        imovel_fotos = ImovelFoto.objects.filter(imovel=imovel)
        context = {"imovel": imovel, "imovel_fotos": imovel_fotos}
        return render(request, 'ver_imovel.html', context)
    

def contato(request):
    if request.method == "POST":
        dados = request.POST.dict()
        contato = Contato.objects.create(nome=dados.get("nome"), 
                                         email=dados.get("email"), 
                                         assunto=dados.get("assunto"),
                                         telefone=dados.get("telefone"),
                                         mensagem=dados.get("mensagem"))
        contato.save()
        return redirect("homepage")        
    else:
        context = {}
        return render(request, "contato.html", context)

monthoya/website/templates/backup/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Imobiliária Monthoya</title>

    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
      integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>
  <body>
    {% include 'navbar.html' %} 
    {% block body %} 
    
    {% endblock %}
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  </body>
</html>

monthoya/website/templates/backup/contato.html
{% extends "base.html" %} {% load static %} {% block body %}

<h2> realize seu contato sobre qualquer imóvel</h2>
<form method="POST" action="{% url 'contato' %}">
    {% csrf_token %}
    <input type="text" name="nome" placeholder="Nome">
    <input type="text" name="email" placeholder="E-mail">
    <input type="text" name="assunto" placeholder="Assunto">
    <input type="text" name="telefone" placeholder="Telefone">
    <textarea id="mensagem" name="mensagem" rows="6" cols="50">
    </textarea>

    <button type="submit">Realizar Contato</button>
</form>


{% endblock %}

monthoya/website/templates/backup/homepage.html
{% extends "base.html" %} 
{% load static %} 

{% block body %}
<h3>Home Page</h3>

<h2>Imóveis em destaque</h2>
{% for imovel in imoveis_destaque %}
    <p>
        <a href="{% url 'ver_imovel' imovel.id %}">
            <img src="{{ imovel.thumbnail.url }}" width="300">
        </a>        
        <br>
        Nome: {{ imovel.titulo }}
        <br>
        Preço: {{ imovel.preco }}
    </p>
{% endfor %} 


<h2>Bairros</h2>
{% for bairro in bairros %}
    <p>
        {{ bairro.descricao }}
    </p>
    {% for imovel in bairro.imovel_set.all %}
        <p>
            <a href="{% url 'ver_imovel' imovel.id %}">
                <img src="{{ imovel.thumbnail.url }}" width="150">
            </a>        
            <br>
            Nome: {{ imovel.titulo }}
            <br>
            Preço: {{ imovel.preco }}
        </p>
    {% endfor %} 
{% endfor %} 

{% endblock %}

monthoya/website/templates/backup/imoveis-views.html
{% extends "base.html" %} 
{% load static %} 
{% load l10n %}

{% block body %} 
<h3>Loja</h3>

<h2>Imóveis Mais Visualizados</h2>
{% for imovel in imoveis_views %}
    <p>
        <a href="{% url 'ver_imovel' imovel.id %}">
            <img src="{{ imovel.thumbnail.url }}" width="300">
        </a>        
        <br>
        Nome: {{ imovel.titulo }} - {{imovel.views}}
        <br>
        Preço: {{ imovel.preco }}        
    </p>
{% endfor %} 

{% endblock %}

monthoya/website/templates/backup/imoveis.html
{% extends "base.html" %} 
{% load static %} 
{% load l10n %}

{% block body %} 
<h3>Loja</h3>

<div style="display: flex;">
    <div>
        Ordenar por:
        <ul>
            <li><a href="#" class="item-ordenar" name="menor-preco">Menor Preço</a></li>
            <li><a href="#" class="item-ordenar" name="maior-preco">Maior Preço</a></li>
            <li><a href="#" class="item-ordenar" name="mais-vendidos">Mais visualizados</a></li>
        </ul>
        {% for imovel in imoveis %} 
            <p>
                <a href="{% url 'ver_imovel' imovel.id %}">
                    <img src="{{ imovel.thumbnail.url }}" width="300">
                </a>        
                <br>
                Nome: {{ imovel.titulo }}
                <br>
                Preço: {{ imovel.preco }}
                <hr>
            </p>
        {% endfor %}
    </div>
</div>
{% endblock %}

monthoya/website/templates/backup/navbar.html
{% load static %}
<nav>
  <a href="{% url 'homepage' %}">Home</a>
  <a href="{% url 'imoveis' %}">Imóveis</a>
  <a href="{% url 'imoveis_views' %}">Mais Visualizados</a>
  <a href="#">Lançamentos</a>
  <a href="#">Sobre</a>
  <a href="#">Cadastre seu imóvel</a>
  <a href="{% url 'contato' %}">Fale Conosco</a>

</nav>

monthoya/website/templates/backup/ver_imovel.html
{% extends "base.html" %} {% load static %} {% block body %}


    <h3>{{ imovel.titulo }}</h3>
    <p>        
        Nome: {{ imovel.id }}
        <br>
        Preço: {{ imovel.preco }} 
    </p>
    <div>        
        {% for imovel_foto in imovel_fotos %} 
            <img src="{{ imovel_foto.imagem.url }}" width="300" height="200">
        {% endfor %}
    </div>

    
    <h2>Videos</h2>


    <h2> Realize seu contato sobre este imóvel</h2>
    <form method="POST" action="{% url 'ver_imovel' imovel.id %}">
        {% csrf_token %}
        <input type="text" name="nome" placeholder="Nome">
        <input type="text" name="email" placeholder="E-mail">
        <input type="text" name="assunto" placeholder="Assunto">
        <input type="text" name="telefone" placeholder="Telefone">
        <textarea id="mensagem" name="mensagem" rows="6" cols="50">
        </textarea>

        <button type="submit">Realizar Contato</button>
    </form>


{% endblock %}

monthoya/website/templates/carrossel.html
{% load static %}
<section class="carrossel">
  <div class="carrossel__botoes">
    <div class="carrossel__botao">
      <div class="carrossel__preenchimento"></div>
    </div>
    <div class="carrossel__botao">
      <div class="carrossel__preenchimento"></div>
    </div>
  </div>

  <div class="carrossel__imagens">          
    <div class="carrossel__item">
      <a href="https://www.usereserva.com/faca-vc">
        <img
          src="{% static 'Imagens/lotes-cascavel.jpg' %}"
          alt="Imagem 1 Desktop"
        />
        <img
          src="https://lojausereserva.vtexassets.com/assets/vtex.file-manager-graphql/images/63f0c2c3-c1ab-4406-88f1-5565c2d23e9e___a4ffcc92bda5a2b1d7ad07117e698745.jpg"
          alt="Imagem 1 Mobile"
        />
      </a>
    </div>
    <div class="carrossel__item">
      <a href="https://www.usereserva.com/faca-vc">
        <img
          src="{% static 'Imagens/banner-casa-nova.jpg' %}"
          alt="Imagem 2 Desktop"
        /><img
          src="https://lojausereserva.vtexassets.com/assets/vtex.file-manager-graphql/images/a7294ce0-496e-4b2b-b87a-d1cd73eb0eb2___6563aa4bdc15c2c7354efe77ccc86d5f.jpg"
          alt="Imagem 2 Mobile"
        />
      </a>
    </div>
  </div>
</section>

monthoya/website/templates/contato.html
{% extends "base.html" %} {% load static %} {% block body %}

<h2> realize seu contato sobre qualquer imóvel</h2>
<form method="POST" action="{% url 'contato' %}">
    {% csrf_token %}
    <input type="text" name="nome" placeholder="Nome">
    <input type="text" name="email" placeholder="E-mail">
    <input type="text" name="assunto" placeholder="Assunto">
    <input type="text" name="telefone" placeholder="Telefone">
    <textarea id="mensagem" name="mensagem" rows="6" cols="50">
    </textarea>

    <button type="submit">Realizar Contato</button>
</form>


{% endblock %}

monthoya/website/templates/imoveis-views.html
{% extends "base.html" %} 
{% load static %} 
{% load l10n %}

{% block body %} 
<h3>Loja</h3>

<h2>Imóveis Mais Visualizados</h2>
{% for imovel in imoveis_views %}
    <p>
        <a href="{% url 'ver_imovel' imovel.id %}">
            <img src="{{ imovel.thumbnail.url }}" width="300">
        </a>        
        <br>
        Nome: {{ imovel.titulo }} - {{imovel.views}}
        <br>
        Preço: {{ imovel.preco }}        
    </p>
{% endfor %} 

{% endblock %}

monthoya/website/templates/imoveis.html
{% extends "base.html" %} 
{% load static %} 
{% load l10n %}

{% block body %} 
<h3>Loja</h3>

<div style="display: flex;">
    <div>
        Ordenar por:
        <ul>
            <li><a href="#" class="item-ordenar" name="menor-preco">Menor Preço</a></li>
            <li><a href="#" class="item-ordenar" name="maior-preco">Maior Preço</a></li>
            <li><a href="#" class="item-ordenar" name="mais-vendidos">Mais visualizados</a></li>
        </ul>
        {% for imovel in imoveis %} 
            <p>
                <a href="{% url 'ver_imovel' imovel.id %}">
                    <img src="{{ imovel.thumbnail.url }}" width="300">
                </a>        
                <br>
                Nome: {{ imovel.titulo }}
                <br>
                Preço: {{ imovel.preco }}
                <hr>
            </p>
        {% endfor %}
    </div>
</div>
{% endblock %}

monthoya/website/templates/navbar.html
{% load static %}
<nav>
  <a href="{% url 'homepage' %}">Home</a>
  <a href="{% url 'imoveis' %}">Imóveis</a>
  <a href="{% url 'imoveis_views' %}">Mais Visualizados</a>
  <a href="#">Lançamentos</a>
  <a href="#">Sobre</a>
  <a href="#">Cadastre seu imóvel</a>
  <a href="{% url 'contato' %}">Fale Conosco</a>

</nav>

monthoya/website/templates/ver_imovel.html
{% extends "base.html" %} {% load static %} {% block body %}


    <h3>{{ imovel.titulo }}</h3>
    <p>        
        Nome: {{ imovel.id }}
        <br>
        Preço: {{ imovel.preco }} 
    </p>
    <div>        
        {% for imovel_foto in imovel_fotos %} 
            <img src="{{ imovel_foto.imagem.url }}" width="300" height="200">
        {% endfor %}
    </div>

    
    <h2>Videos</h2>


    <h2> Realize seu contato sobre este imóvel</h2>
    <form method="POST" action="{% url 'ver_imovel' imovel.id %}">
        {% csrf_token %}
        <input type="text" name="nome" placeholder="Nome">
        <input type="text" name="email" placeholder="E-mail">
        <input type="text" name="assunto" placeholder="Assunto">
        <input type="text" name="telefone" placeholder="Telefone">
        <textarea id="mensagem" name="mensagem" rows="6" cols="50">
        </textarea>

        <button type="submit">Realizar Contato</button>
    </form>


{% endblock %}